// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBGameState.proto

package server.messages;

public final class PBGameStateOuterClass {
  private PBGameStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PBGameStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.messages.PBGameState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
     */
    boolean hasCreatureStat();
    /**
     * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
     */
    server.messages.PBCreatureOuterClass.PBCreature getCreatureStat();
    /**
     * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
     */
    server.messages.PBCreatureOuterClass.PBCreatureOrBuilder getCreatureStatOrBuilder();

    /**
     * <code>optional .server.messages.PBFood food_stat = 2;</code>
     */
    boolean hasFoodStat();
    /**
     * <code>optional .server.messages.PBFood food_stat = 2;</code>
     */
    server.messages.PBFoodOuterClass.PBFood getFoodStat();
    /**
     * <code>optional .server.messages.PBFood food_stat = 2;</code>
     */
    server.messages.PBFoodOuterClass.PBFoodOrBuilder getFoodStatOrBuilder();
  }
  /**
   * Protobuf type {@code server.messages.PBGameState}
   */
  public  static final class PBGameState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server.messages.PBGameState)
      PBGameStateOrBuilder {
    // Use PBGameState.newBuilder() to construct.
    private PBGameState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBGameState() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBGameState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              server.messages.PBCreatureOuterClass.PBCreature.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = creatureStat_.toBuilder();
              }
              creatureStat_ = input.readMessage(server.messages.PBCreatureOuterClass.PBCreature.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(creatureStat_);
                creatureStat_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              server.messages.PBFoodOuterClass.PBFood.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = foodStat_.toBuilder();
              }
              foodStat_ = input.readMessage(server.messages.PBFoodOuterClass.PBFood.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(foodStat_);
                foodStat_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server.messages.PBGameStateOuterClass.internal_static_server_messages_PBGameState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server.messages.PBGameStateOuterClass.internal_static_server_messages_PBGameState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              server.messages.PBGameStateOuterClass.PBGameState.class, server.messages.PBGameStateOuterClass.PBGameState.Builder.class);
    }

    private int bitField0_;
    public static final int CREATURE_STAT_FIELD_NUMBER = 1;
    private server.messages.PBCreatureOuterClass.PBCreature creatureStat_;
    /**
     * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
     */
    public boolean hasCreatureStat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
     */
    public server.messages.PBCreatureOuterClass.PBCreature getCreatureStat() {
      return creatureStat_ == null ? server.messages.PBCreatureOuterClass.PBCreature.getDefaultInstance() : creatureStat_;
    }
    /**
     * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
     */
    public server.messages.PBCreatureOuterClass.PBCreatureOrBuilder getCreatureStatOrBuilder() {
      return creatureStat_ == null ? server.messages.PBCreatureOuterClass.PBCreature.getDefaultInstance() : creatureStat_;
    }

    public static final int FOOD_STAT_FIELD_NUMBER = 2;
    private server.messages.PBFoodOuterClass.PBFood foodStat_;
    /**
     * <code>optional .server.messages.PBFood food_stat = 2;</code>
     */
    public boolean hasFoodStat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .server.messages.PBFood food_stat = 2;</code>
     */
    public server.messages.PBFoodOuterClass.PBFood getFoodStat() {
      return foodStat_ == null ? server.messages.PBFoodOuterClass.PBFood.getDefaultInstance() : foodStat_;
    }
    /**
     * <code>optional .server.messages.PBFood food_stat = 2;</code>
     */
    public server.messages.PBFoodOuterClass.PBFoodOrBuilder getFoodStatOrBuilder() {
      return foodStat_ == null ? server.messages.PBFoodOuterClass.PBFood.getDefaultInstance() : foodStat_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasCreatureStat()) {
        if (!getCreatureStat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasFoodStat()) {
        if (!getFoodStat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getCreatureStat());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getFoodStat());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCreatureStat());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFoodStat());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof server.messages.PBGameStateOuterClass.PBGameState)) {
        return super.equals(obj);
      }
      server.messages.PBGameStateOuterClass.PBGameState other = (server.messages.PBGameStateOuterClass.PBGameState) obj;

      boolean result = true;
      result = result && (hasCreatureStat() == other.hasCreatureStat());
      if (hasCreatureStat()) {
        result = result && getCreatureStat()
            .equals(other.getCreatureStat());
      }
      result = result && (hasFoodStat() == other.hasFoodStat());
      if (hasFoodStat()) {
        result = result && getFoodStat()
            .equals(other.getFoodStat());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCreatureStat()) {
        hash = (37 * hash) + CREATURE_STAT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatureStat().hashCode();
      }
      if (hasFoodStat()) {
        hash = (37 * hash) + FOOD_STAT_FIELD_NUMBER;
        hash = (53 * hash) + getFoodStat().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(server.messages.PBGameStateOuterClass.PBGameState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.messages.PBGameState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.messages.PBGameState)
        server.messages.PBGameStateOuterClass.PBGameStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server.messages.PBGameStateOuterClass.internal_static_server_messages_PBGameState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server.messages.PBGameStateOuterClass.internal_static_server_messages_PBGameState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                server.messages.PBGameStateOuterClass.PBGameState.class, server.messages.PBGameStateOuterClass.PBGameState.Builder.class);
      }

      // Construct using server.messages.PBGameStateOuterClass.PBGameState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCreatureStatFieldBuilder();
          getFoodStatFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (creatureStatBuilder_ == null) {
          creatureStat_ = null;
        } else {
          creatureStatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (foodStatBuilder_ == null) {
          foodStat_ = null;
        } else {
          foodStatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return server.messages.PBGameStateOuterClass.internal_static_server_messages_PBGameState_descriptor;
      }

      public server.messages.PBGameStateOuterClass.PBGameState getDefaultInstanceForType() {
        return server.messages.PBGameStateOuterClass.PBGameState.getDefaultInstance();
      }

      public server.messages.PBGameStateOuterClass.PBGameState build() {
        server.messages.PBGameStateOuterClass.PBGameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public server.messages.PBGameStateOuterClass.PBGameState buildPartial() {
        server.messages.PBGameStateOuterClass.PBGameState result = new server.messages.PBGameStateOuterClass.PBGameState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (creatureStatBuilder_ == null) {
          result.creatureStat_ = creatureStat_;
        } else {
          result.creatureStat_ = creatureStatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (foodStatBuilder_ == null) {
          result.foodStat_ = foodStat_;
        } else {
          result.foodStat_ = foodStatBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof server.messages.PBGameStateOuterClass.PBGameState) {
          return mergeFrom((server.messages.PBGameStateOuterClass.PBGameState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(server.messages.PBGameStateOuterClass.PBGameState other) {
        if (other == server.messages.PBGameStateOuterClass.PBGameState.getDefaultInstance()) return this;
        if (other.hasCreatureStat()) {
          mergeCreatureStat(other.getCreatureStat());
        }
        if (other.hasFoodStat()) {
          mergeFoodStat(other.getFoodStat());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasCreatureStat()) {
          if (!getCreatureStat().isInitialized()) {
            return false;
          }
        }
        if (hasFoodStat()) {
          if (!getFoodStat().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        server.messages.PBGameStateOuterClass.PBGameState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (server.messages.PBGameStateOuterClass.PBGameState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private server.messages.PBCreatureOuterClass.PBCreature creatureStat_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          server.messages.PBCreatureOuterClass.PBCreature, server.messages.PBCreatureOuterClass.PBCreature.Builder, server.messages.PBCreatureOuterClass.PBCreatureOrBuilder> creatureStatBuilder_;
      /**
       * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
       */
      public boolean hasCreatureStat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
       */
      public server.messages.PBCreatureOuterClass.PBCreature getCreatureStat() {
        if (creatureStatBuilder_ == null) {
          return creatureStat_ == null ? server.messages.PBCreatureOuterClass.PBCreature.getDefaultInstance() : creatureStat_;
        } else {
          return creatureStatBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder setCreatureStat(server.messages.PBCreatureOuterClass.PBCreature value) {
        if (creatureStatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          creatureStat_ = value;
          onChanged();
        } else {
          creatureStatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder setCreatureStat(
          server.messages.PBCreatureOuterClass.PBCreature.Builder builderForValue) {
        if (creatureStatBuilder_ == null) {
          creatureStat_ = builderForValue.build();
          onChanged();
        } else {
          creatureStatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder mergeCreatureStat(server.messages.PBCreatureOuterClass.PBCreature value) {
        if (creatureStatBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              creatureStat_ != null &&
              creatureStat_ != server.messages.PBCreatureOuterClass.PBCreature.getDefaultInstance()) {
            creatureStat_ =
              server.messages.PBCreatureOuterClass.PBCreature.newBuilder(creatureStat_).mergeFrom(value).buildPartial();
          } else {
            creatureStat_ = value;
          }
          onChanged();
        } else {
          creatureStatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder clearCreatureStat() {
        if (creatureStatBuilder_ == null) {
          creatureStat_ = null;
          onChanged();
        } else {
          creatureStatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
       */
      public server.messages.PBCreatureOuterClass.PBCreature.Builder getCreatureStatBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCreatureStatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
       */
      public server.messages.PBCreatureOuterClass.PBCreatureOrBuilder getCreatureStatOrBuilder() {
        if (creatureStatBuilder_ != null) {
          return creatureStatBuilder_.getMessageOrBuilder();
        } else {
          return creatureStat_ == null ?
              server.messages.PBCreatureOuterClass.PBCreature.getDefaultInstance() : creatureStat_;
        }
      }
      /**
       * <code>optional .server.messages.PBCreature creature_stat = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          server.messages.PBCreatureOuterClass.PBCreature, server.messages.PBCreatureOuterClass.PBCreature.Builder, server.messages.PBCreatureOuterClass.PBCreatureOrBuilder> 
          getCreatureStatFieldBuilder() {
        if (creatureStatBuilder_ == null) {
          creatureStatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              server.messages.PBCreatureOuterClass.PBCreature, server.messages.PBCreatureOuterClass.PBCreature.Builder, server.messages.PBCreatureOuterClass.PBCreatureOrBuilder>(
                  getCreatureStat(),
                  getParentForChildren(),
                  isClean());
          creatureStat_ = null;
        }
        return creatureStatBuilder_;
      }

      private server.messages.PBFoodOuterClass.PBFood foodStat_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          server.messages.PBFoodOuterClass.PBFood, server.messages.PBFoodOuterClass.PBFood.Builder, server.messages.PBFoodOuterClass.PBFoodOrBuilder> foodStatBuilder_;
      /**
       * <code>optional .server.messages.PBFood food_stat = 2;</code>
       */
      public boolean hasFoodStat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .server.messages.PBFood food_stat = 2;</code>
       */
      public server.messages.PBFoodOuterClass.PBFood getFoodStat() {
        if (foodStatBuilder_ == null) {
          return foodStat_ == null ? server.messages.PBFoodOuterClass.PBFood.getDefaultInstance() : foodStat_;
        } else {
          return foodStatBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder setFoodStat(server.messages.PBFoodOuterClass.PBFood value) {
        if (foodStatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          foodStat_ = value;
          onChanged();
        } else {
          foodStatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder setFoodStat(
          server.messages.PBFoodOuterClass.PBFood.Builder builderForValue) {
        if (foodStatBuilder_ == null) {
          foodStat_ = builderForValue.build();
          onChanged();
        } else {
          foodStatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder mergeFoodStat(server.messages.PBFoodOuterClass.PBFood value) {
        if (foodStatBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              foodStat_ != null &&
              foodStat_ != server.messages.PBFoodOuterClass.PBFood.getDefaultInstance()) {
            foodStat_ =
              server.messages.PBFoodOuterClass.PBFood.newBuilder(foodStat_).mergeFrom(value).buildPartial();
          } else {
            foodStat_ = value;
          }
          onChanged();
        } else {
          foodStatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder clearFoodStat() {
        if (foodStatBuilder_ == null) {
          foodStat_ = null;
          onChanged();
        } else {
          foodStatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .server.messages.PBFood food_stat = 2;</code>
       */
      public server.messages.PBFoodOuterClass.PBFood.Builder getFoodStatBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFoodStatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .server.messages.PBFood food_stat = 2;</code>
       */
      public server.messages.PBFoodOuterClass.PBFoodOrBuilder getFoodStatOrBuilder() {
        if (foodStatBuilder_ != null) {
          return foodStatBuilder_.getMessageOrBuilder();
        } else {
          return foodStat_ == null ?
              server.messages.PBFoodOuterClass.PBFood.getDefaultInstance() : foodStat_;
        }
      }
      /**
       * <code>optional .server.messages.PBFood food_stat = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          server.messages.PBFoodOuterClass.PBFood, server.messages.PBFoodOuterClass.PBFood.Builder, server.messages.PBFoodOuterClass.PBFoodOrBuilder> 
          getFoodStatFieldBuilder() {
        if (foodStatBuilder_ == null) {
          foodStatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              server.messages.PBFoodOuterClass.PBFood, server.messages.PBFoodOuterClass.PBFood.Builder, server.messages.PBFoodOuterClass.PBFoodOrBuilder>(
                  getFoodStat(),
                  getParentForChildren(),
                  isClean());
          foodStat_ = null;
        }
        return foodStatBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server.messages.PBGameState)
    }

    // @@protoc_insertion_point(class_scope:server.messages.PBGameState)
    private static final server.messages.PBGameStateOuterClass.PBGameState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new server.messages.PBGameStateOuterClass.PBGameState();
    }

    public static server.messages.PBGameStateOuterClass.PBGameState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PBGameState>
        PARSER = new com.google.protobuf.AbstractParser<PBGameState>() {
      public PBGameState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBGameState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBGameState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBGameState> getParserForType() {
      return PARSER;
    }

    public server.messages.PBGameStateOuterClass.PBGameState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_messages_PBGameState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_messages_PBGameState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PBGameState.proto\022\017server.messages\032\020PB" +
      "Creature.proto\032\014PBFood.proto\"m\n\013PBGameSt" +
      "ate\0222\n\rcreature_stat\030\001 \001(\0132\033.server.mess" +
      "ages.PBCreature\022*\n\tfood_stat\030\002 \001(\0132\027.ser" +
      "ver.messages.PBFood"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          server.messages.PBCreatureOuterClass.getDescriptor(),
          server.messages.PBFoodOuterClass.getDescriptor(),
        }, assigner);
    internal_static_server_messages_PBGameState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_messages_PBGameState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_messages_PBGameState_descriptor,
        new java.lang.String[] { "CreatureStat", "FoodStat", });
    server.messages.PBCreatureOuterClass.getDescriptor();
    server.messages.PBFoodOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
