// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBGameState.proto

package server.messages;

public final class PBGameStateOuterClass {
  private PBGameStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PBGameStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.messages.PBGameState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
     */
    java.util.List<server.messages.PBCreatureOuterClass.PBCreature> 
        getCreatureStatList();
    /**
     * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
     */
    server.messages.PBCreatureOuterClass.PBCreature getCreatureStat(int index);
    /**
     * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
     */
    int getCreatureStatCount();
    /**
     * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
     */
    java.util.List<? extends server.messages.PBCreatureOuterClass.PBCreatureOrBuilder> 
        getCreatureStatOrBuilderList();
    /**
     * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
     */
    server.messages.PBCreatureOuterClass.PBCreatureOrBuilder getCreatureStatOrBuilder(
        int index);

    /**
     * <code>repeated .server.messages.PBFood food_stat = 2;</code>
     */
    java.util.List<server.messages.PBFoodOuterClass.PBFood> 
        getFoodStatList();
    /**
     * <code>repeated .server.messages.PBFood food_stat = 2;</code>
     */
    server.messages.PBFoodOuterClass.PBFood getFoodStat(int index);
    /**
     * <code>repeated .server.messages.PBFood food_stat = 2;</code>
     */
    int getFoodStatCount();
    /**
     * <code>repeated .server.messages.PBFood food_stat = 2;</code>
     */
    java.util.List<? extends server.messages.PBFoodOuterClass.PBFoodOrBuilder> 
        getFoodStatOrBuilderList();
    /**
     * <code>repeated .server.messages.PBFood food_stat = 2;</code>
     */
    server.messages.PBFoodOuterClass.PBFoodOrBuilder getFoodStatOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code server.messages.PBGameState}
   */
  public  static final class PBGameState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server.messages.PBGameState)
      PBGameStateOrBuilder {
    // Use PBGameState.newBuilder() to construct.
    private PBGameState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBGameState() {
      creatureStat_ = java.util.Collections.emptyList();
      foodStat_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBGameState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                creatureStat_ = new java.util.ArrayList<server.messages.PBCreatureOuterClass.PBCreature>();
                mutable_bitField0_ |= 0x00000001;
              }
              creatureStat_.add(
                  input.readMessage(server.messages.PBCreatureOuterClass.PBCreature.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                foodStat_ = new java.util.ArrayList<server.messages.PBFoodOuterClass.PBFood>();
                mutable_bitField0_ |= 0x00000002;
              }
              foodStat_.add(
                  input.readMessage(server.messages.PBFoodOuterClass.PBFood.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          creatureStat_ = java.util.Collections.unmodifiableList(creatureStat_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          foodStat_ = java.util.Collections.unmodifiableList(foodStat_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server.messages.PBGameStateOuterClass.internal_static_server_messages_PBGameState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server.messages.PBGameStateOuterClass.internal_static_server_messages_PBGameState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              server.messages.PBGameStateOuterClass.PBGameState.class, server.messages.PBGameStateOuterClass.PBGameState.Builder.class);
    }

    public static final int CREATURE_STAT_FIELD_NUMBER = 1;
    private java.util.List<server.messages.PBCreatureOuterClass.PBCreature> creatureStat_;
    /**
     * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
     */
    public java.util.List<server.messages.PBCreatureOuterClass.PBCreature> getCreatureStatList() {
      return creatureStat_;
    }
    /**
     * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
     */
    public java.util.List<? extends server.messages.PBCreatureOuterClass.PBCreatureOrBuilder> 
        getCreatureStatOrBuilderList() {
      return creatureStat_;
    }
    /**
     * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
     */
    public int getCreatureStatCount() {
      return creatureStat_.size();
    }
    /**
     * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
     */
    public server.messages.PBCreatureOuterClass.PBCreature getCreatureStat(int index) {
      return creatureStat_.get(index);
    }
    /**
     * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
     */
    public server.messages.PBCreatureOuterClass.PBCreatureOrBuilder getCreatureStatOrBuilder(
        int index) {
      return creatureStat_.get(index);
    }

    public static final int FOOD_STAT_FIELD_NUMBER = 2;
    private java.util.List<server.messages.PBFoodOuterClass.PBFood> foodStat_;
    /**
     * <code>repeated .server.messages.PBFood food_stat = 2;</code>
     */
    public java.util.List<server.messages.PBFoodOuterClass.PBFood> getFoodStatList() {
      return foodStat_;
    }
    /**
     * <code>repeated .server.messages.PBFood food_stat = 2;</code>
     */
    public java.util.List<? extends server.messages.PBFoodOuterClass.PBFoodOrBuilder> 
        getFoodStatOrBuilderList() {
      return foodStat_;
    }
    /**
     * <code>repeated .server.messages.PBFood food_stat = 2;</code>
     */
    public int getFoodStatCount() {
      return foodStat_.size();
    }
    /**
     * <code>repeated .server.messages.PBFood food_stat = 2;</code>
     */
    public server.messages.PBFoodOuterClass.PBFood getFoodStat(int index) {
      return foodStat_.get(index);
    }
    /**
     * <code>repeated .server.messages.PBFood food_stat = 2;</code>
     */
    public server.messages.PBFoodOuterClass.PBFoodOrBuilder getFoodStatOrBuilder(
        int index) {
      return foodStat_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getCreatureStatCount(); i++) {
        if (!getCreatureStat(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getFoodStatCount(); i++) {
        if (!getFoodStat(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < creatureStat_.size(); i++) {
        output.writeMessage(1, creatureStat_.get(i));
      }
      for (int i = 0; i < foodStat_.size(); i++) {
        output.writeMessage(2, foodStat_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < creatureStat_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, creatureStat_.get(i));
      }
      for (int i = 0; i < foodStat_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, foodStat_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof server.messages.PBGameStateOuterClass.PBGameState)) {
        return super.equals(obj);
      }
      server.messages.PBGameStateOuterClass.PBGameState other = (server.messages.PBGameStateOuterClass.PBGameState) obj;

      boolean result = true;
      result = result && getCreatureStatList()
          .equals(other.getCreatureStatList());
      result = result && getFoodStatList()
          .equals(other.getFoodStatList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getCreatureStatCount() > 0) {
        hash = (37 * hash) + CREATURE_STAT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatureStatList().hashCode();
      }
      if (getFoodStatCount() > 0) {
        hash = (37 * hash) + FOOD_STAT_FIELD_NUMBER;
        hash = (53 * hash) + getFoodStatList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.messages.PBGameStateOuterClass.PBGameState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(server.messages.PBGameStateOuterClass.PBGameState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.messages.PBGameState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.messages.PBGameState)
        server.messages.PBGameStateOuterClass.PBGameStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server.messages.PBGameStateOuterClass.internal_static_server_messages_PBGameState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server.messages.PBGameStateOuterClass.internal_static_server_messages_PBGameState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                server.messages.PBGameStateOuterClass.PBGameState.class, server.messages.PBGameStateOuterClass.PBGameState.Builder.class);
      }

      // Construct using server.messages.PBGameStateOuterClass.PBGameState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCreatureStatFieldBuilder();
          getFoodStatFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (creatureStatBuilder_ == null) {
          creatureStat_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          creatureStatBuilder_.clear();
        }
        if (foodStatBuilder_ == null) {
          foodStat_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          foodStatBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return server.messages.PBGameStateOuterClass.internal_static_server_messages_PBGameState_descriptor;
      }

      public server.messages.PBGameStateOuterClass.PBGameState getDefaultInstanceForType() {
        return server.messages.PBGameStateOuterClass.PBGameState.getDefaultInstance();
      }

      public server.messages.PBGameStateOuterClass.PBGameState build() {
        server.messages.PBGameStateOuterClass.PBGameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public server.messages.PBGameStateOuterClass.PBGameState buildPartial() {
        server.messages.PBGameStateOuterClass.PBGameState result = new server.messages.PBGameStateOuterClass.PBGameState(this);
        int from_bitField0_ = bitField0_;
        if (creatureStatBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            creatureStat_ = java.util.Collections.unmodifiableList(creatureStat_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.creatureStat_ = creatureStat_;
        } else {
          result.creatureStat_ = creatureStatBuilder_.build();
        }
        if (foodStatBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            foodStat_ = java.util.Collections.unmodifiableList(foodStat_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.foodStat_ = foodStat_;
        } else {
          result.foodStat_ = foodStatBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof server.messages.PBGameStateOuterClass.PBGameState) {
          return mergeFrom((server.messages.PBGameStateOuterClass.PBGameState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(server.messages.PBGameStateOuterClass.PBGameState other) {
        if (other == server.messages.PBGameStateOuterClass.PBGameState.getDefaultInstance()) return this;
        if (creatureStatBuilder_ == null) {
          if (!other.creatureStat_.isEmpty()) {
            if (creatureStat_.isEmpty()) {
              creatureStat_ = other.creatureStat_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCreatureStatIsMutable();
              creatureStat_.addAll(other.creatureStat_);
            }
            onChanged();
          }
        } else {
          if (!other.creatureStat_.isEmpty()) {
            if (creatureStatBuilder_.isEmpty()) {
              creatureStatBuilder_.dispose();
              creatureStatBuilder_ = null;
              creatureStat_ = other.creatureStat_;
              bitField0_ = (bitField0_ & ~0x00000001);
              creatureStatBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCreatureStatFieldBuilder() : null;
            } else {
              creatureStatBuilder_.addAllMessages(other.creatureStat_);
            }
          }
        }
        if (foodStatBuilder_ == null) {
          if (!other.foodStat_.isEmpty()) {
            if (foodStat_.isEmpty()) {
              foodStat_ = other.foodStat_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFoodStatIsMutable();
              foodStat_.addAll(other.foodStat_);
            }
            onChanged();
          }
        } else {
          if (!other.foodStat_.isEmpty()) {
            if (foodStatBuilder_.isEmpty()) {
              foodStatBuilder_.dispose();
              foodStatBuilder_ = null;
              foodStat_ = other.foodStat_;
              bitField0_ = (bitField0_ & ~0x00000002);
              foodStatBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFoodStatFieldBuilder() : null;
            } else {
              foodStatBuilder_.addAllMessages(other.foodStat_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCreatureStatCount(); i++) {
          if (!getCreatureStat(i).isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getFoodStatCount(); i++) {
          if (!getFoodStat(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        server.messages.PBGameStateOuterClass.PBGameState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (server.messages.PBGameStateOuterClass.PBGameState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<server.messages.PBCreatureOuterClass.PBCreature> creatureStat_ =
        java.util.Collections.emptyList();
      private void ensureCreatureStatIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          creatureStat_ = new java.util.ArrayList<server.messages.PBCreatureOuterClass.PBCreature>(creatureStat_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          server.messages.PBCreatureOuterClass.PBCreature, server.messages.PBCreatureOuterClass.PBCreature.Builder, server.messages.PBCreatureOuterClass.PBCreatureOrBuilder> creatureStatBuilder_;

      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public java.util.List<server.messages.PBCreatureOuterClass.PBCreature> getCreatureStatList() {
        if (creatureStatBuilder_ == null) {
          return java.util.Collections.unmodifiableList(creatureStat_);
        } else {
          return creatureStatBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public int getCreatureStatCount() {
        if (creatureStatBuilder_ == null) {
          return creatureStat_.size();
        } else {
          return creatureStatBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public server.messages.PBCreatureOuterClass.PBCreature getCreatureStat(int index) {
        if (creatureStatBuilder_ == null) {
          return creatureStat_.get(index);
        } else {
          return creatureStatBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder setCreatureStat(
          int index, server.messages.PBCreatureOuterClass.PBCreature value) {
        if (creatureStatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCreatureStatIsMutable();
          creatureStat_.set(index, value);
          onChanged();
        } else {
          creatureStatBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder setCreatureStat(
          int index, server.messages.PBCreatureOuterClass.PBCreature.Builder builderForValue) {
        if (creatureStatBuilder_ == null) {
          ensureCreatureStatIsMutable();
          creatureStat_.set(index, builderForValue.build());
          onChanged();
        } else {
          creatureStatBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder addCreatureStat(server.messages.PBCreatureOuterClass.PBCreature value) {
        if (creatureStatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCreatureStatIsMutable();
          creatureStat_.add(value);
          onChanged();
        } else {
          creatureStatBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder addCreatureStat(
          int index, server.messages.PBCreatureOuterClass.PBCreature value) {
        if (creatureStatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCreatureStatIsMutable();
          creatureStat_.add(index, value);
          onChanged();
        } else {
          creatureStatBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder addCreatureStat(
          server.messages.PBCreatureOuterClass.PBCreature.Builder builderForValue) {
        if (creatureStatBuilder_ == null) {
          ensureCreatureStatIsMutable();
          creatureStat_.add(builderForValue.build());
          onChanged();
        } else {
          creatureStatBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder addCreatureStat(
          int index, server.messages.PBCreatureOuterClass.PBCreature.Builder builderForValue) {
        if (creatureStatBuilder_ == null) {
          ensureCreatureStatIsMutable();
          creatureStat_.add(index, builderForValue.build());
          onChanged();
        } else {
          creatureStatBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder addAllCreatureStat(
          java.lang.Iterable<? extends server.messages.PBCreatureOuterClass.PBCreature> values) {
        if (creatureStatBuilder_ == null) {
          ensureCreatureStatIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, creatureStat_);
          onChanged();
        } else {
          creatureStatBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder clearCreatureStat() {
        if (creatureStatBuilder_ == null) {
          creatureStat_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          creatureStatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public Builder removeCreatureStat(int index) {
        if (creatureStatBuilder_ == null) {
          ensureCreatureStatIsMutable();
          creatureStat_.remove(index);
          onChanged();
        } else {
          creatureStatBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public server.messages.PBCreatureOuterClass.PBCreature.Builder getCreatureStatBuilder(
          int index) {
        return getCreatureStatFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public server.messages.PBCreatureOuterClass.PBCreatureOrBuilder getCreatureStatOrBuilder(
          int index) {
        if (creatureStatBuilder_ == null) {
          return creatureStat_.get(index);  } else {
          return creatureStatBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public java.util.List<? extends server.messages.PBCreatureOuterClass.PBCreatureOrBuilder> 
           getCreatureStatOrBuilderList() {
        if (creatureStatBuilder_ != null) {
          return creatureStatBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(creatureStat_);
        }
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public server.messages.PBCreatureOuterClass.PBCreature.Builder addCreatureStatBuilder() {
        return getCreatureStatFieldBuilder().addBuilder(
            server.messages.PBCreatureOuterClass.PBCreature.getDefaultInstance());
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public server.messages.PBCreatureOuterClass.PBCreature.Builder addCreatureStatBuilder(
          int index) {
        return getCreatureStatFieldBuilder().addBuilder(
            index, server.messages.PBCreatureOuterClass.PBCreature.getDefaultInstance());
      }
      /**
       * <code>repeated .server.messages.PBCreature creature_stat = 1;</code>
       */
      public java.util.List<server.messages.PBCreatureOuterClass.PBCreature.Builder> 
           getCreatureStatBuilderList() {
        return getCreatureStatFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          server.messages.PBCreatureOuterClass.PBCreature, server.messages.PBCreatureOuterClass.PBCreature.Builder, server.messages.PBCreatureOuterClass.PBCreatureOrBuilder> 
          getCreatureStatFieldBuilder() {
        if (creatureStatBuilder_ == null) {
          creatureStatBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              server.messages.PBCreatureOuterClass.PBCreature, server.messages.PBCreatureOuterClass.PBCreature.Builder, server.messages.PBCreatureOuterClass.PBCreatureOrBuilder>(
                  creatureStat_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          creatureStat_ = null;
        }
        return creatureStatBuilder_;
      }

      private java.util.List<server.messages.PBFoodOuterClass.PBFood> foodStat_ =
        java.util.Collections.emptyList();
      private void ensureFoodStatIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          foodStat_ = new java.util.ArrayList<server.messages.PBFoodOuterClass.PBFood>(foodStat_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          server.messages.PBFoodOuterClass.PBFood, server.messages.PBFoodOuterClass.PBFood.Builder, server.messages.PBFoodOuterClass.PBFoodOrBuilder> foodStatBuilder_;

      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public java.util.List<server.messages.PBFoodOuterClass.PBFood> getFoodStatList() {
        if (foodStatBuilder_ == null) {
          return java.util.Collections.unmodifiableList(foodStat_);
        } else {
          return foodStatBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public int getFoodStatCount() {
        if (foodStatBuilder_ == null) {
          return foodStat_.size();
        } else {
          return foodStatBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public server.messages.PBFoodOuterClass.PBFood getFoodStat(int index) {
        if (foodStatBuilder_ == null) {
          return foodStat_.get(index);
        } else {
          return foodStatBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder setFoodStat(
          int index, server.messages.PBFoodOuterClass.PBFood value) {
        if (foodStatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFoodStatIsMutable();
          foodStat_.set(index, value);
          onChanged();
        } else {
          foodStatBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder setFoodStat(
          int index, server.messages.PBFoodOuterClass.PBFood.Builder builderForValue) {
        if (foodStatBuilder_ == null) {
          ensureFoodStatIsMutable();
          foodStat_.set(index, builderForValue.build());
          onChanged();
        } else {
          foodStatBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder addFoodStat(server.messages.PBFoodOuterClass.PBFood value) {
        if (foodStatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFoodStatIsMutable();
          foodStat_.add(value);
          onChanged();
        } else {
          foodStatBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder addFoodStat(
          int index, server.messages.PBFoodOuterClass.PBFood value) {
        if (foodStatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFoodStatIsMutable();
          foodStat_.add(index, value);
          onChanged();
        } else {
          foodStatBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder addFoodStat(
          server.messages.PBFoodOuterClass.PBFood.Builder builderForValue) {
        if (foodStatBuilder_ == null) {
          ensureFoodStatIsMutable();
          foodStat_.add(builderForValue.build());
          onChanged();
        } else {
          foodStatBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder addFoodStat(
          int index, server.messages.PBFoodOuterClass.PBFood.Builder builderForValue) {
        if (foodStatBuilder_ == null) {
          ensureFoodStatIsMutable();
          foodStat_.add(index, builderForValue.build());
          onChanged();
        } else {
          foodStatBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder addAllFoodStat(
          java.lang.Iterable<? extends server.messages.PBFoodOuterClass.PBFood> values) {
        if (foodStatBuilder_ == null) {
          ensureFoodStatIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, foodStat_);
          onChanged();
        } else {
          foodStatBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder clearFoodStat() {
        if (foodStatBuilder_ == null) {
          foodStat_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          foodStatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public Builder removeFoodStat(int index) {
        if (foodStatBuilder_ == null) {
          ensureFoodStatIsMutable();
          foodStat_.remove(index);
          onChanged();
        } else {
          foodStatBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public server.messages.PBFoodOuterClass.PBFood.Builder getFoodStatBuilder(
          int index) {
        return getFoodStatFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public server.messages.PBFoodOuterClass.PBFoodOrBuilder getFoodStatOrBuilder(
          int index) {
        if (foodStatBuilder_ == null) {
          return foodStat_.get(index);  } else {
          return foodStatBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public java.util.List<? extends server.messages.PBFoodOuterClass.PBFoodOrBuilder> 
           getFoodStatOrBuilderList() {
        if (foodStatBuilder_ != null) {
          return foodStatBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(foodStat_);
        }
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public server.messages.PBFoodOuterClass.PBFood.Builder addFoodStatBuilder() {
        return getFoodStatFieldBuilder().addBuilder(
            server.messages.PBFoodOuterClass.PBFood.getDefaultInstance());
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public server.messages.PBFoodOuterClass.PBFood.Builder addFoodStatBuilder(
          int index) {
        return getFoodStatFieldBuilder().addBuilder(
            index, server.messages.PBFoodOuterClass.PBFood.getDefaultInstance());
      }
      /**
       * <code>repeated .server.messages.PBFood food_stat = 2;</code>
       */
      public java.util.List<server.messages.PBFoodOuterClass.PBFood.Builder> 
           getFoodStatBuilderList() {
        return getFoodStatFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          server.messages.PBFoodOuterClass.PBFood, server.messages.PBFoodOuterClass.PBFood.Builder, server.messages.PBFoodOuterClass.PBFoodOrBuilder> 
          getFoodStatFieldBuilder() {
        if (foodStatBuilder_ == null) {
          foodStatBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              server.messages.PBFoodOuterClass.PBFood, server.messages.PBFoodOuterClass.PBFood.Builder, server.messages.PBFoodOuterClass.PBFoodOrBuilder>(
                  foodStat_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          foodStat_ = null;
        }
        return foodStatBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server.messages.PBGameState)
    }

    // @@protoc_insertion_point(class_scope:server.messages.PBGameState)
    private static final server.messages.PBGameStateOuterClass.PBGameState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new server.messages.PBGameStateOuterClass.PBGameState();
    }

    public static server.messages.PBGameStateOuterClass.PBGameState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PBGameState>
        PARSER = new com.google.protobuf.AbstractParser<PBGameState>() {
      public PBGameState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBGameState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBGameState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBGameState> getParserForType() {
      return PARSER;
    }

    public server.messages.PBGameStateOuterClass.PBGameState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_messages_PBGameState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_messages_PBGameState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PBGameState.proto\022\017server.messages\032\020PB" +
      "gameobjects.Creature.proto\032\014PBFood.proto\"m\n\013PBGameSt" +
      "ate\0222\n\rcreature_stat\030\001 \003(\0132\033.server.mess" +
      "ages.PBCreature\022*\n\tfood_stat\030\002 \003(\0132\027.ser" +
      "ver.messages.PBFood"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          server.messages.PBCreatureOuterClass.getDescriptor(),
          server.messages.PBFoodOuterClass.getDescriptor(),
        }, assigner);
    internal_static_server_messages_PBGameState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_messages_PBGameState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_messages_PBGameState_descriptor,
        new java.lang.String[] { "CreatureStat", "FoodStat", });
    server.messages.PBCreatureOuterClass.getDescriptor();
    server.messages.PBFoodOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
