// automatically generated by the FlatBuffers compiler, do not modify

package AI.Obs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Score extends Table {
  public static Score getRootAsScore(ByteBuffer _bb) { return getRootAsScore(_bb, new Score()); }
  public static Score getRootAsScore(ByteBuffer _bb, Score obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Score __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int id() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public float fitness() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createScore(FlatBufferBuilder builder,
      int id,
      float fitness) {
    builder.startObject(2);
    Score.addFitness(builder, fitness);
    Score.addId(builder, id);
    return Score.endScore(builder);
  }

  public static void startScore(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addId(FlatBufferBuilder builder, int id) { builder.addShort(0, (short)id, 0); }
  public static void addFitness(FlatBufferBuilder builder, float fitness) { builder.addFloat(1, fitness, 0.0f); }
  public static int endScore(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

