// automatically generated by the FlatBuffers compiler, do not modify

package sim.messages.AI.Obs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Smell extends Table {
  public static Smell getRootAsSmell(ByteBuffer _bb) { return getRootAsSmell(_bb, new Smell()); }
  public static Smell getRootAsSmell(ByteBuffer _bb, Smell obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Smell __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public float protein() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float starch() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float fat() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createSmell(FlatBufferBuilder builder,
      float protein,
      float starch,
      float fat) {
    builder.startObject(3);
    Smell.addFat(builder, fat);
    Smell.addStarch(builder, starch);
    Smell.addProtein(builder, protein);
    return Smell.endSmell(builder);
  }

  public static void startSmell(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addProtein(FlatBufferBuilder builder, float protein) { builder.addFloat(0, protein, 0.0f); }
  public static void addStarch(FlatBufferBuilder builder, float starch) { builder.addFloat(1, starch, 0.0f); }
  public static void addFat(FlatBufferBuilder builder, float fat) { builder.addFloat(2, fat, 0.0f); }
  public static int endSmell(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

