// automatically generated by the FlatBuffers compiler, do not modify

package sim.messages.AI.Obs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Smell extends Struct {
  public Smell __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public float protein() { return bb.getFloat(bb_pos + 0); }
  public float starch() { return bb.getFloat(bb_pos + 4); }
  public float fat() { return bb.getFloat(bb_pos + 8); }

  public static int createSmell(FlatBufferBuilder builder, float protein, float starch, float fat) {
    builder.prep(4, 12);
    builder.putFloat(fat);
    builder.putFloat(starch);
    builder.putFloat(protein);
    return builder.offset();
  }
}

